name: Binance FIX API

concurrency:
  group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  SERVICE: binance_fix_api

jobs:
  lint:
    name: Run golangci-lint
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.58.2
          args: --config=.golangci.yml
          skip-pkg-cache: true
          skip-build-cache: true

  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
      - name: Run test
        run: go test -race -v ./...
